import bookcover from '../assets/bookexample.svg';
import bookcover2 from '../assets/dummyBook2.svg';
export const mockBooks = [
  {
    id: 1,
    title: '밤의 여행자들',
    author: '윤고은',
    category: '소설/시/희곡',
    coverImage: bookcover,
  },
  {
    id: 2,
    title: '이기적 유전자',
    author: '리처드 도킨스',
    category: '소설/시/희곡',
    coverImage: bookcover2,
  },
];

export const mockRooms = [
  {
    id: 1,
    book: '이기적 유전자',
    author: '리처드 도킨스',
    category: '소설/시/희곡',
    title: 'testroom',
    currentpeople: 5,
    totalpeople: 6,
    progress: '30',
    startdate: '2024.12.30',
    enddate: '2025.01.20',
    coverImage: bookcover2,
    isLocked: true,
  },
  {
    id: 2,
    book: '이기적 유전자',
    author: '리처드 도킨스',
    category: '소설/시/희곡',
    title: 'testroom',
    currentpeople: 3,
    totalpeople: 5,
    progress: '30',
    startdate: '2024.12.30',
    enddate: '2025.01.20',
    coverImage: bookcover2,
    isLocked: false,
  },
  {
    id: 3,
    book: '밤의 여행자들',
    author: '윤고은',
    category: '소설/시/희곡',
    title: 'notlocked',
    currentpeople: 5,
    totalpeople: 10,
    progress: '40',
    startdate: '2025.01.02',
    enddate: '2025.01.31',
    coverImage: bookcover,
    isLocked: false,
  },
  {
    id: 4,
    book: '밤의 여행자들',
    author: '윤고은',
    category: '소설/시/희곡',
    title: 'lockedroom',
    currentpeople: 5,
    totalpeople: 20,
    progress: '70',
    startdate: '2025.01.13',
    enddate: '2025.02.02',
    coverImage: bookcover,
    isLocked: true,
  },
];
